# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-22 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treasures',
            new_name='Treasure',
        ),
    ]
